import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My First App",
  description: "Generated by create next app",
  keywords: 'next, react, app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/solar/bootstrap.min.css"/>
      </head>

      <body className={inter.className}>
        <Navigation/>
        <div className="container p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
